version: '3.8'

services: 
    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env.prod
    
    django:
        build: 
            context: ./django
            dockerfile: Dockerfile.prod
        command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on: 
            - postgres
    
    sapper:
        build: 
            context: ./sapper
            dockerfile: Dockerfile.prod
            args:
                API_SERVER_URL: http://django:8000/api/article
                API_CLIENT_URL: http://localhost:1337/api/article
        command: node __sapper__/build
        expose:
            - 3000
        env_file:
            - ./.env.prod
        depends_on:
            - django
    
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
        ports:
            - 1337:80
        depends_on: 
            - django

volumes:
    postgres_data:
    static_volume: