version: '3.8'

services: 
    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env.dev
    
    django:
        build: ./django
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - postgres

volumes:
    postgres_data: