version: '3.8'

services: 
    postgres:
        restart: always
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env.prod
    
    django:
        build: 
            context: ./django
            dockerfile: Dockerfile.prod
        command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on: 
            - postgres
    
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.prod
        volumes:
            - static_volume:/home/app/web/staticfiles
        ports:
            - 1337:80
        depends_on: 
            - django

volumes:
    postgres_data:
    static_volume: